# Generated by Django 6.0.3 on 2026-03-06 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('KGS', 'KGS - Киргизский сом'), ('RUB', 'RUB - Российский рубль'), ('USD', 'USD - Доллар США'), ('CNY', 'CNY - Китайский юань')], max_length=3)),
                ('to_currency', models.CharField(choices=[('KGS', 'KGS - Киргизский сом'), ('RUB', 'RUB - Российский рубль'), ('USD', 'USD - Доллар США'), ('CNY', 'CNY - Китайский юань')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Курс обмена', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.DecimalField(decimal_places=2, help_text='Сумма к оплате (KGS)', max_digits=10)),
                ('currency_from', models.CharField(default='KGS', max_length=3)),
                ('amount_to', models.DecimalField(decimal_places=2, help_text='Сумма зачисления (CNY)', max_digits=10)),
                ('currency_to', models.CharField(default='CNY', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Применённый курс', max_digits=10)),
                ('recipient_account', models.CharField(help_text='Кошелёк/телефон получателя (AliPay)', max_length=255)),
                ('receipt_image', models.ImageField(help_text='Скриншот чека', upload_to='receipts/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'На проверке'), ('COMPLETED', 'Выполнено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10)),
                ('manager_comment', models.TextField(blank=True, help_text='Комментарий менеджера (при отклонении)', null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Применённая скидка %', max_digits=4)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Сумма скидки', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Итоговая сумма к оплате', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.service')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, help_text='Номер счета/карты', max_length=255)),
                ('qr_code', models.ImageField(blank=True, help_text='QR-код для оплаты', null=True, upload_to='payment/qr/')),
                ('recipient_name', models.CharField(blank=True, help_text='Получатель', max_length=255)),
                ('additional_info', models.TextField(blank=True, help_text='Дополнительная информация для клиента')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='orders.bank')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='orders.service')),
            ],
            options={
                'verbose_name': 'Платёжные реквизиты',
                'verbose_name_plural': 'Платёжные реквизиты',
                'unique_together': {('service', 'bank')},
            },
        ),
    ]
