# Generated by Django 6.0.3 on 2026-03-06 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='banks/logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-слаг'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='from_currency',
            field=models.CharField(choices=[('KGS', 'KGS - Киргизский сом'), ('RUB', 'RUB - Российский рубль'), ('USD', 'USD - Доллар США'), ('CNY', 'CNY - Китайский юань')], max_length=3, verbose_name='Валюта отдачи'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Курс обмена валют', max_digits=10, verbose_name='Курс обмена'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='to_currency',
            field=models.CharField(choices=[('KGS', 'KGS - Киргизский сом'), ('RUB', 'RUB - Российский рубль'), ('USD', 'USD - Доллар США'), ('CNY', 'CNY - Китайский юань')], max_length=3, verbose_name='Валюта получения'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, help_text='Сумма к оплате (KGS)', max_digits=10, verbose_name='Сумма к оплате'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, help_text='Сумма зачисления (CNY)', max_digits=10, verbose_name='Сумма зачисления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency_from',
            field=models.CharField(default='KGS', max_length=3, verbose_name='Валюта оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency_to',
            field=models.CharField(default='CNY', max_length=3, verbose_name='Валюта зачисления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма скидки в валюте получения', max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Применённая скидка в процентах', max_digits=4, verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, help_text='Курс обмена, применённый к операции', max_digits=10, verbose_name='Применённый курс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, help_text='Итоговая сумма после всех расчётов', max_digits=10, verbose_name='Итоговая сумма к оплате'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, help_text='Комментарий менеджера (при отклонении)', null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_image',
            field=models.ImageField(help_text='Скриншот чека об оплате', upload_to='receipts/%Y/%m/%d/', verbose_name='Чек об оплате'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_account',
            field=models.CharField(help_text='Кошелёк/телефон получателя (AliPay)', max_length=255, verbose_name='Счёт получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'На проверке'), ('COMPLETED', 'Выполнено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='account_number',
            field=models.CharField(blank=True, help_text='Номер счёта или карты для оплаты', max_length=255, verbose_name='Номер счёта/карты'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Дополнительная информация для клиента', verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='orders.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR-код для быстрой оплаты', null=True, upload_to='payment/qr/', verbose_name='QR-код для оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='ФИО получателя платежа', max_length=255, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='orders.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-слаг'),
        ),
    ]
