# Generated by Django 6.0.3 on 2026-03-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_bank_created_at_alter_bank_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_qr_code',
            field=models.ImageField(blank=True, help_text='QR-код кошелька/счёта получателя', null=True, upload_to='receipts/qr/%Y/%m/%d/', verbose_name='QR-код получателя'),
        ),
    ]
