# Generated by Django 6.0.3 on 2026-03-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_recipient_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_account',
            field=models.CharField(blank=True, help_text='Кошелёк/телефон получателя (AliPay). Если не указан, используется QR-код из профиля', max_length=255, null=True, verbose_name='Счёт получателя'),
        ),
    ]
