# Generated by Django 6.0.3 on 2026-03-06 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_first_order_discount_used_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, help_text='4-значный пин-код для быстрых операций', max_length=4, null=True, verbose_name='PIN-код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_order_discount_used',
            field=models.BooleanField(default=False, verbose_name='Скидка новичка использована'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Накопленные бонусы (сом)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего операций'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Логин (служебное поле)'),
        ),
    ]
