# Generated by Django 6.0.3 on 2026-03-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alipay_qr_code',
            field=models.ImageField(blank=True, help_text='QR-код кошелька AliPay пользователя', null=True, upload_to='users/alipay_qr/%Y/%m/%d/', verbose_name='QR-код AliPay'),
        ),
    ]
