# Generated by Django 6.0.3 on 2026-03-06 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Push отправлен'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Текст уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Заявка создана'), ('ORDER_COMPLETED', 'Заявка выполнена'), ('ORDER_REJECTED', 'Заявка отклонена'), ('BONUS_RECEIVED', 'Бонус получен'), ('PROMO', 'Акция'), ('SYSTEM', 'Системное')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип связанного объекта'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='device_info',
            field=models.CharField(blank=True, help_text='Название браузера или устройства', max_length=255, verbose_name='Информация об устройстве'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='device_type',
            field=models.CharField(default='web', help_text='web, ios, android', max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='token',
            field=models.CharField(max_length=500, unique=True, verbose_name='Push-токен'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
